[package]
name = "nitro_signer_mock"
version = "0.1.0"
edition = "2021"

[dependencies]
nitro_signer = { path = "../nitro_signer" }
clap = { version = "4.5", features = ["derive"] }
clap_derive = "4.5"
serde = { version = "1.0", features = ["derive"] }
