[package]
name = "vsock"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
num = "0.4"
tokio = { version = "1.42", features = ["net"] }

[dev-dependencies]
tokio = { version = "1.42", features = ["net", "macros", "rt"] }
tokio-macros = "2.4"
futures = "0.3"
