[package]
name = "nitro_signer_app"
version = "0.1.0"
edition = "2021"

[dependencies]
nitro_signer = { path = "../nitro_signer" }
vsock = { path = "../vsock" }
aws-nitro-enclaves-nsm-api = "0.4"
libc = "0.2"
